name: one_drop
description: "One Drop - Blood Donation & Emergency Finder App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  introduction_screen: ^4.0.0
  shared_preferences: ^2.2.2
  country_flags: ^4.1.2
  pinput: ^6.0.2
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  shimmer: ^3.0.0
  http: ^1.6.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/data/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/app_icon.png
  android: true
  ios: true

  android_12:
    color: "#FFFFFF"
    
    image: assets/icons/app_icon.png
