// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRijukMfdoLV5ihCc9drb-i67rwNiRTSs',
    appId: '1:679440989609:web:57eeb5afd1eecdf73e98b8',
    messagingSenderId: '679440989609',
    projectId: 'one-drop-app-bc675',
    authDomain: 'one-drop-app-bc675.firebaseapp.com',
    storageBucket: 'one-drop-app-bc675.firebasestorage.app',
    measurementId: 'G-NPPX7SECHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuZWx_Jcc3u8UWXVfE6Pa855wyxzINY5w',
    appId: '1:679440989609:android:b30723c698ee4f143e98b8',
    messagingSenderId: '679440989609',
    projectId: 'one-drop-app-bc675',
    storageBucket: 'one-drop-app-bc675.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaH0sKL7QwwWgjQ1IUHOiBziPh9GcAosg',
    appId: '1:679440989609:ios:adc007aeea5fc6343e98b8',
    messagingSenderId: '679440989609',
    projectId: 'one-drop-app-bc675',
    storageBucket: 'one-drop-app-bc675.firebasestorage.app',
    iosBundleId: 'com.example.oneDrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaH0sKL7QwwWgjQ1IUHOiBziPh9GcAosg',
    appId: '1:679440989609:ios:adc007aeea5fc6343e98b8',
    messagingSenderId: '679440989609',
    projectId: 'one-drop-app-bc675',
    storageBucket: 'one-drop-app-bc675.firebasestorage.app',
    iosBundleId: 'com.example.oneDrop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRijukMfdoLV5ihCc9drb-i67rwNiRTSs',
    appId: '1:679440989609:web:8526b7fda23261cc3e98b8',
    messagingSenderId: '679440989609',
    projectId: 'one-drop-app-bc675',
    authDomain: 'one-drop-app-bc675.firebaseapp.com',
    storageBucket: 'one-drop-app-bc675.firebasestorage.app',
    measurementId: 'G-XN3EWJ1GVW',
  );
}